services:
  minecraft-bedrock-server:
    image: minecraft-bedrock-server:latest
    restart: unless-stopped
    volumes:
      - ./data/config:/config
      - ./data/worlds:/worlds
    ports:
      - 28637:19132/udp
